version: "3.8"

services:
  php-app:
    image: goutam24/php-fullstack-app
    ports:
      - "3002:80"
    secrets:
      - db_user
      - db_password
      - db_name
    environment:
      DB_HOST: mysql-app
      DB_USER_FILE: /run/secrets/db_user
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_NAME_FILE: /run/secrets/db_name
    networks:
      - app-net

  mysql-app:
    image: mysql:5.7
    secrets:
      - db_user
      - db_password
      - db_name
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE_FILE: /run/secrets/db_name
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - db_data:/var/lib/mysql
      - ./employees.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-net

volumes:
  db_data:

secrets:
  db_user:
    external: true
  db_password:
    external: true
  db_name:
    external: true

networks:
  app-net:
    driver: overlay
