version: "3.8"

services:
  php-app:
    image: goutam24/php-fullstack-app
    networks:
      - app-net
    ports:
      - "3003:80"  # Expose port 80 in the container as 3003 on the host
    entrypoint: >
      sh -c "
        echo 'Waiting for MySQL...';
        while ! nc -z mysql-app 3306; do
          sleep 2;
        done;
        echo 'MySQL is up. Starting PHP app...';
        php -S 0.0.0.0:80 -t /var/www/html"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  mysql-app:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: demo_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - app-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  app-net:
    driver: overlay
