version: '3.8'

services:
  php-app:
    image: goutam24/php-fullstack-app:latest
    ports:
      - "8081:80"
    depends_on:
      - mysql-app
    networks:
      - app-network

  mysql-app:
    image: mysql:5.7
    container_name: mysql-app
    ports:
      - "3306:3306"
    secrets:
      - db_user
      - db_password
      - db_name
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE_FILE: /run/secrets/db_name
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - db_data:/var/lib/mysql
      - ./employees.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: overlay
    attachable: true

secrets:
  db_user:
    external: true
  db_password:
    external: true
  db_name:
    external: true
